DEBUG 2022-06-16 12:53:50.549 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-16 12:53:50.549 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-16 12:53:50.549 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-16 12:53:50.549 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-16 12:53:50.550 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-16 12:53:50.550 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-16 12:53:50.550 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-16 12:53:50.551 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-16 12:53:50.551 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-16 12:53:50.552 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-16 12:54:09.938 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-16 12:54:09.938 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-16 12:54:09.938 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-16 12:54:09.939 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-16 12:54:09.939 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-16 12:54:09.939 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-16 12:54:09.940 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-16 12:54:09.940 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-16 12:54:09.940 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-16 12:54:09.942 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-16 12:55:02.471 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-16 12:55:02.471 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-16 12:55:02.471 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-16 12:55:02.471 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
ERROR 2022-06-16 12:55:02.472 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2022-06-16 12:55:02.472 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 51, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2022-06-16 12:55:02.473 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-16 12:55:16.839 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-16 12:55:16.839 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-16 12:55:16.839 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-16 12:55:16.839 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-16 12:55:16.840 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-16 12:55:16.840 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-16 12:55:16.840 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-16 12:55:16.840 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-16 12:55:16.841 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-16 12:55:16.843 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-21 13:07:07.305 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-21 13:07:07.305 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-21 13:07:07.305 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-21 13:07:07.305 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-21 13:07:07.306 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-21 13:07:07.306 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-21 13:07:07.307 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-21 13:07:07.307 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-21 13:07:07.307 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-21 13:07:07.309 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-21 13:07:26.460 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-21 13:07:26.460 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-21 13:07:26.460 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-21 13:07:26.460 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-21 13:07:26.461 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-21 13:07:26.461 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-21 13:07:26.461 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-21 13:07:26.461 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-21 13:07:26.461 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-21 13:07:26.463 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-21 13:07:36.250 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-21 13:07:36.251 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-21 13:07:36.251 UTC: 	 Executing command: 'kill'
DEBUG 2022-06-21 13:07:36.251 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
ERROR 2022-06-21 13:07:36.251 UTC: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2022-06-21 13:07:36.251 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 638, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
INFO 2022-06-21 13:07:36.252 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-06-21 13:07:49.724 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-06-21 13:07:49.724 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-06-21 13:07:49.724 UTC: 	 Executing command: 'submit'
DEBUG 2022-06-21 13:07:49.724 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-06-21 13:07:49.725 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-06-21 13:07:49.725 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-06-21 13:07:49.725 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-06-21 13:07:49.725 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-06-21 13:07:49.725 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-06-21 13:07:49.727 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-07-28 12:55:28.464 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-28 12:55:28.465 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-28 12:55:28.465 UTC: 	 Executing command: 'submit'
DEBUG 2022-07-28 12:55:28.465 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-07-28 12:55:28.465 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitWminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-07-28 12:55:28.465 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-07-28 12:55:28.466 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-07-28 12:55:28.467 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-07-28 12:55:28.467 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WminusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-07-28 12:55:28.468 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-07-29 09:44:32.134 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-29 09:44:32.134 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-29 09:44:32.134 UTC: 	 Executing command: 'status'
DEBUG 2022-07-29 09:44:32.134 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
ERROR 2022-07-29 09:44:32.135 UTC: 	 Error: crab_submit/crab_projects/crab_DYJetsToMuMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP/ is not a valid CRAB project directory.
ERROR 2022-07-29 09:44:32.135 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_submit/crab_projects/crab_DYJetsToMuMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP/ is not a valid CRAB project directory.
INFO 2022-07-29 09:44:32.136 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-08-23 12:12:17.034 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-08-23 12:12:17.035 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-08-23 12:12:17.035 UTC: 	 Executing command: 'submit'
DEBUG 2022-08-23 12:12:17.035 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-08-23 12:12:17.035 UTC: 	 Will use CRAB configuration file submitWplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-08-23 12:12:17.035 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-08-23 12:12:17.036 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-08-23 12:12:17.037 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-08-23 12:12:17.037 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-08-23 12:12:17.038 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-08-23 12:13:23.300 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-08-23 12:13:23.300 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-08-23 12:13:23.300 UTC: 	 Executing command: 'submit'
DEBUG 2022-08-23 12:13:23.300 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-08-23 12:13:23.300 UTC: 	 Will use CRAB configuration file submitWplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP.py
DEBUG 2022-08-23 12:13:23.300 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-08-23 12:13:23.301 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-08-23 12:13:23.302 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
ERROR 2022-08-23 12:13:23.302 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_WplusJetsToTauNu_TauToMu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos_MCPostVFP' already exists 
Please change the requestName in the config file
INFO 2022-08-23 12:13:23.303 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:10:58.770 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:10:58.770 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:10:58.770 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:10:58.770 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:10:58.771 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1.py
DEBUG 2022-12-30 01:10:58.771 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:10:58.772 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:10:58.772 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:10:58.772 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:10:58.774 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:10:59.014 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:10:59.015 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:10:59.015 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:10:59.015 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:10:59.015 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1.py
DEBUG 2022-12-30 01:10:59.015 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:10:59.016 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:10:59.016 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:10:59.016 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:10:59.018 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:10:59.261 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:10:59.261 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:10:59.261 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:10:59.261 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:10:59.262 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4.py
DEBUG 2022-12-30 01:10:59.262 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:10:59.263 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:10:59.263 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:10:59.263 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:10:59.264 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:11:30.740 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:11:30.741 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:11:30.741 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:11:30.741 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:11:30.741 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1.py
DEBUG 2022-12-30 01:11:30.741 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:11:30.742 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:11:30.742 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:11:30.742 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016F-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:11:30.743 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:11:30.986 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:11:30.986 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:11:30.986 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:11:30.986 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:11:30.986 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1.py
DEBUG 2022-12-30 01:11:30.986 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:11:30.987 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:11:30.987 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:11:30.987 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016G-21Feb2020_UL2016_WMass_MiniAODv2-v1' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:11:30.989 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2022-12-30 01:11:31.233 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-30 01:11:31.233 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-30 01:11:31.234 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-30 01:11:31.234 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
INFO 2022-12-30 01:11:31.234 UTC: 	 Will use CRAB configuration file /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/submitSingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4.py
DEBUG 2022-12-30 01:11:31.234 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-30 01:11:31.235 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-30 01:11:31.235 UTC: 	 Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4' already exists 
Please change the requestName in the config file
ERROR 2022-12-30 01:11:31.235 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab_projects/crab_SingleMuon_Run2016H-21Feb2020_UL2016_WMass_MiniAODv2-v4' already exists 
Please change the requestName in the config file
INFO 2022-12-30 01:11:31.236 UTC: 	 Log file is /home/k/kelong/work/mWProd/CMSSW_10_6_26/src/Configuration/WMassNanoProduction/crab_submit/crab.log
DEBUG 2023-02-09 14:01:34.864 UTC: 	 CRAB Client version: v3.221018
DEBUG 2023-02-09 14:01:34.864 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-02-09 14:01:34.864 UTC: 	 Executing command: 'submit'
DEBUG 2023-02-09 14:01:34.864 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
DEBUG 2023-02-09 14:01:35.098 UTC: 	 CRAB Client version: v3.221018
DEBUG 2023-02-09 14:01:35.099 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-02-09 14:01:35.099 UTC: 	 Executing command: 'submit'
DEBUG 2023-02-09 14:01:35.099 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
DEBUG 2023-02-09 14:01:35.334 UTC: 	 CRAB Client version: v3.221018
DEBUG 2023-02-09 14:01:35.334 UTC: 	 Running on: Linux lxplus8s10.cern.ch 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-02-09 14:01:35.334 UTC: 	 Executing command: 'submit'
DEBUG 2023-02-09 14:01:35.334 UTC: 	 Found CRAB cache file /home/k/kelong/.crab3
